language: php

dist: bionic

php: 
  - 7.2
  - 7.3
  - 7.4
  - 8.0
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

#install: travis_retry composer install

#script: vendor/bin/phpunit
script: phpunit

jobs:
  allow_failures:
    - php: nightly

#  include:
#    - stage: Metrics and quality
#      php: 7.2
#      env: CODE_STANDARD
#      script:
#        - export PHPCS_DIR=/tmp/phpcs
#        - export PHPCOMPAT_DIR=/tmp/PHPCompatibility
#        - git clone -b master --depth 1 https://github.com/squizlabs/PHP_CodeSniffer.git $PHPCS_DIR
#        - $PHPCS_DIR/bin/phpcs --config-set installed_paths $PHPCOMPAT_DIR
#        - phpenv rehash
#        - $PHPCS_DIR/bin/phpcs .

#    - stage: Metrics and quality
#      php: 7.2
#      env: PHPSTAN
#      script:
#        - export PHPSTAN_DIR=/tmp/PHPSTAN
#        - git clone -b master --depth 1 https://github.com/phpstan/phpstan.git $PHPSTAN_DIR        
#        - $PHPSTAN_DIR/phpstan analyse -c phpstan.neon           
        